-- CreateEnum
CREATE TYPE "UserRole" AS ENUM ('USER', 'ADMIN');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "role" "UserRole" NOT NULL DEFAULT 'USER';

-- AlterTable
ALTER TABLE "camisasfutebol" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "descricao" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "imagens" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "nome" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "preco" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "time" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "modelo" SET DEFAULT '',
ALTER COLUMN "versao" SET DEFAULT '',
ALTER COLUMN "tamanho" SET DEFAULT '';
